[[redirects]]
  from = "/cct/*"
  to = "/cct/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/pbi_accuracy/*"
  to = "/pbi_accuracy/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/landing/index.html"
  status = 200

[build]
  command = "npm run build && cd pbi_accuracy && npm install && npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 