[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cct"
  to = "/cct/"
  status = 301
  force = true

[[redirects]]
  from = "/cct/*"
  to = "/cct/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/cct/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 