[[redirects]]
  from = "/cct/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/landing/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 